# Generated by Django 5.0.6 on 2024-07-04 03:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del curso')),
                ('precio', models.PositiveIntegerField(verbose_name='Precio')),
                ('cursos', models.CharField(choices=[('Clase B', 'Clase B'), ('Clase A2', 'Clase A2'), ('Clase A3', 'Clase A3')], max_length=20, verbose_name='Cursos')),
                ('descripcion', models.TextField(verbose_name='Descripción del curso')),
                ('imagen_curso', models.ImageField(upload_to='cursos/', verbose_name='Imagen Curso')),
            ],
        ),
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_curso', models.CharField(max_length=100, verbose_name='Nombre del curso')),
                ('fecha_pedido', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de compra')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio')),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Completado', 'Completado'), ('Cancelado', 'Cancelado')], max_length=50, verbose_name='Estado')),
                ('perfil', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Perfil')),
            ],
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_estudiante', models.CharField(max_length=50, unique=True, verbose_name='Nombre de estudiante')),
                ('rut', models.CharField(blank=True, max_length=10, null=True, unique=True, verbose_name='RUT')),
                ('correo', models.EmailField(max_length=254, unique=True, verbose_name='Correo Electrónico')),
                ('cursos', models.CharField(choices=[('Clase B', 'Clase B'), ('Clase A2', 'Clase A2'), ('Clase A3', 'Clase A3')], max_length=20, verbose_name='Cursos')),
                ('direccion', models.CharField(blank=True, max_length=255, null=True, verbose_name='Dirección')),
                ('foto_perfil', models.ImageField(blank=True, null=True, upload_to='usuarios/', verbose_name='Foto de perfil')),
                ('rol', models.CharField(choices=[('Administrador', 'Administrador'), ('Estudiante', 'Estudiante')], max_length=20, verbose_name='Rol')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DetalleCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_pago', models.CharField(choices=[('Credito', 'Credito'), ('Debito', 'Debito'), ('Transferencia', 'Transferencia')], max_length=30, verbose_name='Tipo de Pago')),
                ('compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='aplicacion.compra')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='aplicacion.producto')),
            ],
        ),
        migrations.CreateModel(
            name='CarritoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('compra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='aplicacion.compra')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicacion.producto')),
            ],
        ),
    ]
