# Generated by Django 5.0.6 on 2024-07-05 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0002_producto_cupos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carritoitem',
            name='cantidad',
        ),
        migrations.RemoveField(
            model_name='detallecompra',
            name='tipo_pago',
        ),
    ]
